appname: "docker-registry"
port: 5000
runtime: "python"
build:
    - "pip install -i http://pypi.douban.com/simple/ ./depends/docker-registry-core && pip install -i http://pypi.douban.com/simple/ file:///docker-registry && pip install -i http://pypi.douban.com/simple/ mysql-python"
cmd:
    - "gunicorn -c gunicorn_config.py app:application"
services:
    - "mysql"
    - "redis"
