appname: "docker-registry"
port: 5000
runtime: "python"
build:
    - "pip install -i http://pypi.douban.com/simple/ ./depends/docker-registry-core && pip install -i http://pypi.douban.com/simple/ ./docker-registry#egg=docker-registry[bugsnag,newrelic]"
cmd:
    - "python app.py"
# 需要mount吧
