DOCKER_REGISTRY_CONFIG: "./docker-registry-config.yml"
SETTINGS_FLAVOR: "prod"
INDEX_ENDPOINT: "http://registry.intra.hunantv.com"
SQLALCHEMY_INDEX_DATABASE: "mysql://registry:#8SQMU'Z6+@10.1.201.58:3306/registry"
CACHE_REDIS_HOST: "10.1.201.88"
CACHE_REDIS_PORT: "2001"
CACHE_LRU_REDIS_HOST: "10.1.201.88"
CACHE_LRU_REDIS_PORT: "2002"
SMTP_HOST: "smtp.exmail.qq.com"
SMTP_LOGIN: "gitlab@gitup.me"
SMTP_PASSWORD: "^123$456a"
SMTP_FROM_ADDR: "docker-registry@gitup.me"
SMTP_TO_ADDR: "noise+dockerregistry@gitup.me"
SEARCH_BACKEND: "sqlalchemy"
STORAGE_PATH: "/data/registry/"
