DOCKER_REGISTRY_CONFIG: "./docker-registry-config.yml"
SETTINGS_FLAVOR: "prod"
INDEX_ENDPOINT: "http://registry.intra.hunantv.com"
CACHE_LRU_REDIS_HOST: "10.1.201.88"
CACHE_LRU_REDIS_PORT: "2002"
SMTP_HOST: "smtp.exmail.qq.com"
SMTP_LOGIN: "gitlab@gitup.me"
SMTP_PASSWORD: "^123$456a"
SMTP_FROM_ADDR: "docker-registry@gitup.me"
SMTP_TO_ADDR: "noise+dockerregistry@gitup.me"
SEARCH_BACKEND: "sqlalchemy"
STORAGE_PATH: "/docker-registry/permdir"
mysql:
    username: "docker-registry"
    password: "#8SQMU'Z6+"
    host: "10.1.201.58"
    port: 3306
    db: "docker-registry"
redis:
    host: "10.1.201.88"
    port: 2001
